image: mrcyjanek/waydroid:ubuntu.20-04
matrix:
 - env: DISTRO=hirsute
   image: mrcyjanek/waydroid:ubuntu.21-04
script:
 - apt update
 - build_changelog
 - mk-build-deps -ir -t "apt-get -o Debug::pkgProblemResolver=yes -y --no-install-recommends"
 - debuild -b -uc -us
 - mkdir -p /apt/$DISTRO/ || true
 - mv ../*.deb /apt/$DISTRO/
